version: "3.9"

services:
  app:
    container_name: whale_app
    build: .

  db:
    container_name: mariadb
    image: mariadb:10.8.3
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ${DB_PATH}:/data
  
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin
    restart: always
    environment:
      - PMA_ARBITRARY=1