name: deploy on server

on:
  push:
    branches:
      - 'dev'
    tags:
      - 'v*'
    
jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}