# https://zellwk.com/blog/github-actions-deploy/
name: deploy on server

on:
  push:
    branches:
      - 'dev'
    tags:
      - 'v*'
    
jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout 
        uses: actions/checkout@v2

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }} 
          known_hosts: 'random_link'

      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      # mb need check folder if it exists and after this drop

      - name: Deploy with rsync
        run: rsync --exclude=".git" -avz -e "ssh -p ${{ secrets.SSH_PORT }}" ./ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/var/www/${{ secrets.PROJECT_FOLDER }}/new-version/

      - name: Rebuild and restart container
        uses: fifsky/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          user: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          command: |
            cd /var/www/${{ secrets.PROJECT_FOLDER }}
            rm -rf /var/www/${{ secrets.PROJECT_FOLDER }}/current
            mkdir current
            mv new-version/* current/
            cd current
          #  docker-compose -f docker-compose.yml -f docker-compose.prod.yml --env-file ./../config/.env up --build --no-deps -d ${{ secrets.APP_NAME }}